# 선형대수 연산들

#### 이번 장에서는 numpy의 함수들을 이용해서 선형대수의 연산을 해보려고 합니다.

In [1]:
import numpy as np

### 벡터의 내적 (dot product or inner product)

In [2]:
a = [1, 2, 3, 4]
b = [2, 0, 1, 5]

In [3]:
np.vdot(a, b)

25

### 행렬의 내적 (also refer to 'inner' function)

In [4]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]

In [5]:
np.dot(a, b)

array([[4, 1],
       [2, 2]])

#### 벡터가 아닌 행렬에 vdot연산을 사용할 경우 행렬이 벡터로 바뀝니다.

In [6]:
np.vdot(a, b)

6

### 단위행렬(identity matrix) 

In [7]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### 행렬의 곱셈

In [8]:
a = np.eye(2)
b = [[4, 1], [2, 2]]

In [9]:
np.matmul(a, b)

array([[ 4.,  1.],
       [ 2.,  2.]])

### 원하는 모양의 행렬 만들기

In [10]:
a = np.arange(9).reshape(3, 3)

In [11]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### trace 구하기

In [12]:
np.trace(a)

12

### 행렬식(determinant 구하기)

In [13]:
import numpy.linalg as LA

In [14]:
a = [[1, 2], [3, 4]]

In [15]:
LA.det(a)

-2.0000000000000004

### Ax = b 의 해 x 구하기

In [16]:
A = np.array([[3,1], [1,2]])
b = np.array([9,8])

In [17]:
LA.solve(A, b)

array([ 2.,  3.])

### 역행렬 구하기

In [18]:
A = [[1, 2], [3, 4]]

In [19]:
LA.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])